export const FETCH_SAVED_VIDEOS_SUCCESS = 'FETCH_SAVED_VIDEOS_SUCCESS';

export const OPEN_SNACK_BAR = 'OPEN_SNACK_BAR';
export const CLOSE_SNACK_BAR = 'CLOSE_SNACK_BAR';

export const OPEN_VIDEO_MODAL = 'OPEN_VIDEO_MODAL';
export const CLOSE_VIDEO_MODAL = 'CLOSE_VIDEO_MODAL';
